import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { MatDatepickerModule } from '@angular/material/datepicker';
import {
  MatToolbarModule,
  MatMenuModule,
  MatSidenavModule,
  MatStepperModule,
  MatFormFieldModule,
  MatDividerModule,
  MatInputModule,
  MatProgressBarModule,
  MatButtonModule,
  MatRippleModule,
  MatListModule,
  MatCheckboxModule,
  MatProgressSpinnerModule,
  MatCardModule,
  MatGridListModule,
  MatIconModule,
  MatDialogModule,
} from '@angular/material';
@NgModule({
  imports: [MatButtonModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatIconModule,
    MatMenuModule,
    MatSidenavModule,
    MatStepperModule,
    MatFormFieldModule,
    MatDividerModule,
    MatCardModule,
    MatInputModule,
    FormsModule,
    MatProgressBarModule,
    MatRippleModule,
    MatListModule,
    MatGridListModule,
    MatDatepickerModule,
    MatDialogModule,
  ],

  exports: [MatButtonModule,
    MatProgressSpinnerModule,
    MatCheckboxModule,
    MatToolbarModule,
    MatIconModule,
    MatMenuModule,
    MatSidenavModule,
    MatStepperModule,
    MatFormFieldModule,
    MatDividerModule,
    MatCardModule,
    MatInputModule,
    FormsModule,
    MatProgressBarModule,
    MatRippleModule,
    MatListModule,
    MatGridListModule,
    MatDatepickerModule,
    MatDialogModule,
  ],
})
export class MaterialModule { }
